name: Improved detection of fraud cases for e-commerce and bank transactions

on:
  push:
    branches: develop
  pull_request:
    branches: develop

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib seaborn scikit-learn